#!/usr/bin/env bash
set -ex

# Symlinks to ephemeral disks are created here by udev
EPHEMERAL_DISKS=/.bottlerocket/rootfs/dev/disk/ephemeral

# Exit early if there aren't ephemeral disks
if [ ! -d ${EPHEMERAL_DISKS} ]; then
  echo "${EPHEMERAL_DISKS} doesn't exist"
  exit 1
fi

# Use the first ephemeral disk
DISK="$(cd ${EPHEMERAL_DISKS} && readlink -f $(ls | head -n 1))"
# There will be only one partition
PARTITION="${DISK}p1"
# For k8s, use containerd, for ECS use docker
CONTAINER_RUNTIME=containerd
# Path where the disk will be mounted
MOUNT_POINT=/.bottlerocket/rootfs/mnt/${CONTAINER_RUNTIME}
# The path to the container's runtime root
RUNTIME_ROOT_PATH=/.bottlerocket/rootfs/var/lib/${CONTAINER_RUNTIME}

# If the partition doesn't exist, create it
if [ ! -e ${PARTITION} ]; then
  parted -s ${DISK} mklabel gpt 1>/dev/null
  parted -s ${DISK} mkpart primary ext4 0% 100% 1>/dev/null
  mkfs.ext4 -F ${PARTITION}
fi

mkdir -p ${MOUNT_POINT}
mount ${PARTITION} ${MOUNT_POINT}

# If the container's runtime root directory exists, you have to manually delete it
if [ ! -d ${RUNTIME_ROOT_PATH} ]; then
  # Use /mnt since the symlink will be seen from the host's perspective
  ln -snf /mnt/${CONTAINER_RUNTIME} ${RUNTIME_ROOT_PATH}
 fi
