apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  nodeSelector:
    karpenter.sh/provisioner-name: gpu
  tolerations:
  - key: "provisioner"
    value: "gpu"
    operator: "Equal"
    effect: "NoSchedule"
  containers:
  - name: curl
    image: curlimages/curl
    command: [ "sleep", "600" ]
    resources:
      requests:
        nvidia.com/gpu: 1
        cpu: 1
        memory: 256Mi
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /mnt
      name: scratch-volume
  volumes:
  - name: scratch-volume
    hostPath:
      # directory location on host
      path: /mnt/scratch
      # this field is optional
      type: Directory
